{{- if or .Values.serviceMonitor.enabled .Values.communications.teams.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "botkube.fullname" . }}
  labels: 
    app.kubernetes.io/name: {{ include "botkube.name" . }}
    helm.sh/chart: {{ include "botkube.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
    app: botkube
spec:
  {{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  {{- if .Values.serviceMonitor.enabled }}
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.communications.teams.enabled }}
  - name: "teams"
    port: {{ .Values.communications.teams.port }}
  {{- end }}
  selector:
    app: botkube 
{{- end }}
