cert-manager:
  enabled: true
  installCRDs: true

  extraArgs:
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
    - --dns01-recursive-nameservers-only

  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "8.8.8.8"

duckdns:
  token: test

extraEnv:
  TZ: Europe/Berlin

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/arch: amd64
