{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duckdns-go.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "duckdns-go.name" . }}
    chart: {{ include "duckdns-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  token: {{ .Values.duckdns.token | b64enc }}
{{- end }}