name: Lint Charts

on: pull_request

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
        charts: ${{ steps.filter.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/**/*.yaml'

  lint-test:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.charts == 'true')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: ct.yaml